### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ghost** [veethree/KDP#1]
Hello, [according to this forums post](https://love2d.org/forums/viewtopic.php?p=244846&sid=0ef2349b6e1304beab711fb53cb42918#p244846) you intend this code to be available under the MIT license. However, since the project stopped dev the code itself was never marked as such. Could you add a proper license file or otherwise mark the current licensing of the code?

As it stands, making modifications to this puts any developer who does so at some risk since you could turn around and claim you didn't allow them to do so... I'm no lawyer so I can't speculate on how that would work out legally, but it could still cause some chaos for others and makes the project really unattractive to anyone who'd want to continue it.

**Comment by veethree** [comment]
Done.

**Comment by ghost** [comment]
Thank you, for both this change and the *very fast* turnaround time!
